# config/bt/berry_named_pose_test2.yaml
tree_file_path: "/home/wossas/Desktop/strawberry_robotArm/strawberry_ws/src/berry-good-bot/behavior_trees/berryNamedPoseTest2.xml"
register_node_types: ["named_pose_nodes"]
