# config/bt/rough_approach_test1.yaml

tree_file_path: "/home/wossas/Desktop/strawberry_robotArm/strawberry_ws/src/berry-good-bot/behavior_trees/roughApproachBT_test1.xml"
register_node_types: ["named_pose_nodes", "rough_approach_nodes"]
