# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: position_controllers/GripperActionController


    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joint: gripper_joint
    
manipulator_controller:
  ros__parameters:
    joints:
      - screw_joint
      - joint1
      - joint2
      - joint3
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity