name: CI
on: [push, pull_request]

jobs:
  ros_ci:
    uses: ros-tooling/action-ros-ci@v0
    with:
      target-ros2-distro: humble
      package-name: |
        strawberry_core
        strawberry_description
